name: Dependency Cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: prime-cache-eed6d55
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          # Add your dependency directory here (e.g. node_modules, .m2 for Maven, etc.)
        key: cache-eed6d55

    - name: Echo cache hit/miss
      run: echo "Cache result:${{ steps.cache.outputs.cache-hit }}"
